### ISSUE TITLE
Update to DataFusion 43

### ISSUE THREAD

**Issue by Dandandan** [apache/datafusion-ballista#1124]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Update to latest version DataFusion 43. This contains a number of performance improvements / fixes.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by milenkovicm** [comment]
https://github.com/apache/datafusion-ballista/pull/1111 there is open or

**Comment by Dandandan** [comment]
Ah missed the PR...

**Comment by milenkovicm** [comment]
closing #1111 as duplicate
